### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by alireza1219** [shahabsafaei/imdb#2]
🐋

**Comment by alireza1219** [comment]
PR #5 dockerize the development environment.
We'll do the production dockerization once the project is fully completed.

**Comment by shahabsafaei** [comment]
Merged.

**Comment by shahabsafaei** [comment]
Change README.md too.
Add guidance for running it using Docker.

**Comment by alireza1219** [comment]
> Change README.md too. Add guidance for running it using Docker.

Yeah, I was about to mention it here. (You read my mind tbh 😅)
I'll do it tomorrow night. Maybe sooner.

**Comment by shahabsafaei** [comment]
done
